# Default values for edge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
edgeIdOverride: ""

# The scheme to use for the Mezmo API URL (http or https)
mezmoApiScheme: "https"

# The hostname[:port] of the Mezmo API
mezmoApiHost: "api.mezmo.com"

# Your Mezmo API Access Token
mezmoApiAccessToken: ""

# Secret containing your Mezmo API Access Token
mezmoApiAccessSecret: ""

# Deployment group for this Edge instance.
# Setting configures only pipelines tagged with this group name.
# Leaving unset configures all Edge pipelines defined in your org.
mezmoDeploymentGroup: ""


# Remote tasks are for running edge instances that phone home for
# tasks to be run locally.  this includes things like tap requests
# in the UI.  We rate limit these requests to 10/second by default.
# This is the intitial delay before the first poll for remote tasks
remoteTaskInitialPollDelay: "5"
# This is the delay between subsequent polls for remote tasks
remoteTaskPollStepDelay: "2"
# This is the wait timeout for remote task execution response
remoteTaskExecutionTimeout: "60"

logLevel: "info"

image:
  repository: mezmohq/vector
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # Ports that are required operationally by the service
  servicePorts:
    - name: graphql-api
      protocol: TCP
      port: 8686
      targetPort: 8686
  # Ports that are mapped to Pipeline sources
  sourcePorts:
    start: 8000
    end: 8010
    list: []

# Use a DaemonSet to run one instance of the Edge agent on each node.
useDaemonSet: false
# When false, a StatefulSet is used to run a minimum of one instance.
replicaCount: 1
# StatefulSet only: autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

secretAnnotations: {}

podSecurityContext: {}

securityContext: {}

imagePullSecrets: []

enableK8sLogs: false

# Optional PersistentVolumeClaim name to use for default storage in statefulset deployments
pvcName: ""

# Optional path for the default host storage for daemonset deployments
daemonsetVolumeHostPath: "/data/edge"

maxDiskBufferBytes: 0
maxMemBufferEvents: 0

# defaults defined as strings to avoid helm treating
# as floats and rendering scientific notation
reduceByteThresholdPerState: "104857600"
reduceByteThresholdAllStates: "1073741824"
tokenSecretRefError: |+


  ######################################################################
  ###  ERROR: Please specify an access token (`mezmoApiAccessToken`) ###
  ###    or a secret containing a token (`mezmoApiAccessSecret`)     ###
  ######################################################################

  Try:

    $ helm upgrade --reuse-values --set mezmoApiAccessToken=<ACCESS_TOKEN> {{ .Release.Name }} mezmo/{{ .Chart.Name }}
