apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulse.fullname" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
{{- if .Values.secretAnnotations }}
  annotations: {{ toYaml .Values.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  api-access-token: {{ default "MISSING" .Values.mezmoApiAccessToken | b64enc | quote }}
