apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
data:
  processor.yaml: |
    provider:
      type: http
      url: ${MEZMO_API_SCHEME}://${MEZMO_API_HOST}/v3/pipeline/account/local-deploy/config
      poll_interval_secs: 15
      request:
        headers:
          authorization: "Token ${MEZMO_LOCAL_DEPLOY_AUTH_TOKEN}"
        {{- $payload := include "edge.heartbeatCommon" . | fromYaml }}
        {{- $has_label := and (ge (.Capabilities.KubeVersion.Major | int) 1) (ge (.Capabilities.KubeVersion.Minor | int) 28) }}
        {{- if $has_label }}
        {{- $_ := set $payload "replica" "${POD_INDEX_LABEL}"}}
        {{- else }}
        {{- $_ := set $payload "replica" "0"}}
        {{- end }}
        payload: {{ toJson $payload | quote }}