apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
data:
  processor.yaml: |
    provider:
      type: http
      url: ${MEZMO_API_SCHEME}://${MEZMO_API_HOST}/v3/pipeline/account/local-deploy/config
      poll_interval_secs: 15
      request:
        headers:
          authorization: "Token ${MEZMO_LOCAL_DEPLOY_AUTH_TOKEN}"
