apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "edge.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.servicePorts }}
    - name: {{ .name }} 
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
    {{- range untilStep (.Values.service.sourcePorts.start|int) (add1 .Values.service.sourcePorts.end | int) 1 }}
    - port: {{ . }}
      name: "tcp-{{ . }}"
    - port: {{ . }}
      name: "udp-{{ . }}"
      protocol: UDP
    {{- end }}
    {{- range (.Values.service.sourcePorts.list) }}
    - port: {{ . }}
      name: "tcp-{{ . }}"
    - port: {{ . }}
      name: "udp-{{ . }}"
      protocol: UDP
    {{- end }}
