apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pulse.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.servicePorts }}
    - name: {{ .name }} 
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
    {{- range untilStep (.Values.service.sourcePorts.start|int) (.Values.service.sourcePorts.end|int) 1 }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: "udp-{{ . }}"
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: "tcp-{{ . }}"
    {{- end }}
